name: 部署游戏到 GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: 发布网站
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 下载游戏代码
        uses: actions/checkout@v4

      - name: 设置 GitHub Pages
        uses: actions/configure-pages@v5

      - name: 打包网站文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: 发布网站
        id: deployment
        uses: actions/deploy-pages@v4
